### ISSUE TITLE
Could not pass event PlayerInteractEvent to Gastronomicon vDEV - 8 (git 76336191)

### ISSUE THREAD

**Issue by IAISI** [SchnTgaiSpock/Gastronomicon#13]
## Description (Required)
```
com.destroystokyo.paper.exception.ServerEventException: Could not pass event PlayerInteractEvent to Gastronomicon vDEV - 8 (git 76336191)
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:72)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
	at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:595)
	at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:536)
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1908)
	at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37)
	at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:9)
	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:53)
	at net.minecraft.server.TickTask.run(TickTask.java:18)
	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1324)
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193)
	at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
	at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1301)
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1294)
	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
	at net.minecraft.server.MinecraftServer.u_(MinecraftServer.java:1272)
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1160)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.getType()" because the return value of "org.bukkit.event.player.PlayerInteractEvent.getItem()" is null
	at SlimefunGastronomicon.jar//io.github.schntgaispock.gastronomicon.core.listeners.FermenterRefillListener.onRefill(FermenterRefillListener.java:49)
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor656.execute(Unknown Source)
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
	at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:595)
	at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:536)
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1908)
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37)
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9)
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:53)
	at net.minecraft.server.TickTask.run(TickTask.java:18)
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153)
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1324)
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193)
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126)
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1301)
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1294)
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136)
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1272)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1160)
	... 2 more
```

## Steps to reproduce the Issue (Required)
Not sure.

## Expected behavior (Required)
Not sure.

## Server Log / Error Report
In description.

## Environment (Required)
```
> sf versions
[19:43:35 INFO]: This Server uses the following setup of Slimefun:
Paper git-Paper-365 (MC: 1.20.4)
Slimefun 4.9-UNOFFICIAL
Metrics-Module #29
Java 17

Installed Addons: (16)
  Networks vDEV - 50 (git 3de3c9d6)
  Gastronomicon vDEV - 8 (git 76336191)
  ExtraTools v1.2
  FastMachines vBuild 13 (git 949e99d)
  SoundMuffler v1.0-SNAPSHOT
  SfChunkInfo vDEV - 8 (git b1b94abb)
  Bump vBuild 40 (git 811005e)
  DynaTech vMain - 6
  ExtraGear vDEV - 13 (git c62047e2)
  SlimefunLuckyBlocks vUNOFFICIAL
  ExoticGarden vUNOFFICIAL
  SlimeHUD vDEV - 11 (git b6dc2d53)
  InfinityExpansion vMODIFIED
  LiteXpansion vMODIFIED
  ExtraHeads vDEV - 25 (git 8c29f73a)
  FluffyMachines v1.0.0

```

**Comment by IAISI** [comment]
Is it possible only null check is missing?

**Comment by SchnTgaiSpock** [comment]
fixed in latest build https://blob.build/project/Gastronomicon
